version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/chromium  # Prevents source code overwrites
    environment:
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_CHROMIUM_PATH=/usr/local/chromium/chrome
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
